In [ ]:
import requests

url = 'https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json'
response = requests.get(url)
datal = response.json()

def func(n):
    return n['available_rent_bikes'] == 0

zero_rent_bikes = list(filter(func,datal))
print(len(zero_rent_bikes))
for site in zero_rent_bikes:
    print(site['sna'])

66
YouBike2.0_和平公園東側
YouBike2.0_復興南路二段340巷口
YouBike2.0_溫州停車場
YouBike2.0_和平龍泉街口
YouBike2.0_捷運古亭站(5號出口)
YouBike2.0_昌隆公園
YouBike2.0_敦化市民路口
YouBike2.0_懷生國中
YouBike2.0_臺灣師範大學(浦城街)
YouBike2.0_民權延平路口(西北側)
YouBike2.0_捷運北門站(3號出口)
YouBike2.0_南京太原路口
YouBike2.0_雙蓮國小
YouBike2.0_南京西寧北路口(西北側)
YouBike2.0_劍潭抽水站
YouBike2.0_銘傳大學
YouBike2.0_社子國小
YouBike2.0_文林路101巷口
YouBike2.0_海光公園南側
YouBike2.0_天母東路8巷/忠誠路二段154巷口
YouBike2.0_景美運動公園
YouBike2.0_興得閱覽室
YouBike2.0_木南公園
YouBike2.0_捷運動物園站(2號出口)
YouBike2.0_名門社區
YouBike2.0_捷運古亭站(9號出口)
YouBike2.0_和平重慶路口
YouBike2.0_捷運小南門站(1號出口)
YouBike2.0_林森徐州路口
YouBike2.0_羅斯福寧波東街口
YouBike2.0_捷運臺大醫院站(1號出口)
YouBike2.0_捷運中正紀念堂站(2號出口)
YouBike2.0_螢橋公園
YouBike2.0_公館水岸廣場
YouBike2.0_捷運行天宮站(3號出口)
YouBike2.0_新生高架停車場(林森北路107巷口)
YouBike2.0_中山北路二段59巷口
YouBike2.0_興安合江路口
YouBike2.0_復華公園
YouBike2.0_敬業三樂群三路口(西北側)
YouBike2.0_長春路258巷2弄口
YouBike2.0_中崙加油站
YouBike2.0_中正國小(南京東路三段48巷)
YouBike2.0_文德二號公園(南側)
YouBike2.0_瑞陽公園
YouBike2.0_碧湖公園(內湖路二段103巷)
YouBike2.0_石潭公園(安康路)
YouBike2.0_奇岩一號公園
YouBike2.0_立功街55巷口
Yo

In [5]:
scores = [78,69,87]
new_scores = []

for score in scores:
    new_scores.append(score+3)

new_scores

[81, 72, 90]

In [6]:
#list comprehention(快速建立list)
scores = [78, 69, 65]
new_scores = [score+3 for score in scores]
new_scores

[81, 72, 68]

In [7]:
scores = [78, 69, 65]
scores * 2

[78, 69, 65, 78, 69, 65]

In [8]:
[67, 92, 85] + [78, 69, 65]

[67, 92, 85, 78, 69, 65]

In [9]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [10]:
scores.sum()
scores.mean()
scores.std()
scores.min()
scores.max()
np.median(scores)

np.float64(69.0)

In [11]:
students = np.array([
    [67, 94, 65],
    [78, 92, 68],
    [59, 92, 87]
    ])
students
#三位學生的三科成績資料

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [12]:
#常用的查詢屬性
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [13]:
students[0,0]

np.int64(67)

In [14]:
#第1位學生分數
students[0,:]

array([67, 94, 65])

In [15]:
#前2個學生
students[0:2,:]

array([[67, 94, 65],
       [78, 92, 68]])

In [22]:
#最後2個學生成績加3分
students[-2:,:] + 3

array([[81, 95, 71],
       [62, 95, 90]])

In [17]:
#第一欄分數
students[:,0]


array([67, 78, 59])

In [18]:
students[:,:2]

array([[67, 94],
       [78, 92],
       [59, 92]])

In [26]:
students[0,0] = 100
students

array([[100,  94,  65],
       [ 78,  92,  68],
       [ 59,  92,  87]])

In [28]:
students[-2:,:] +=3
students[-2:,:]

array([[84, 98, 74],
       [65, 98, 93]])

In [34]:
import pandas as pd
pd.DataFrame(data=students,
             index=['stud1','stud2','stud3'],
             columns =['國文','英文','數學']
             )

國文  英文  數學
stud1  100  94  65
stud2   84  98  74
stud3   65  98  93

In [73]:
dat = np.random.randint(50,high=101,size=(50, 5))
students = pd.DataFrame(dat,
             columns=['國文','英文','數學','地理','探討'])
students

國文   英文   數學  地理   探討
0   86   96   63  73   52
1   60   67   77  62   68
2   65   66   64  63   90
3   75   68   80  74   52
4   89   73   61  70   66
5   72   69   65  88   56
6   53   96   80  59   87
7   86   75   75  90   55
8   69   67   54  91   77
9   74   59   88  61   84
10  66   67   93  87   95
11  71   63   70  50   90
12  98   82   50  72   74
13  74   74   54  84   52
14  61   72   57  57   80
15  77   85   81  77   66
16  73   97   71  69   98
17  98   69   68  84   61
18  80   82   60  73   74
19  75   97   96  65   69
20  95   67   61  69   64
21  60   95   58  98   90
22  71   61   61  96   86
23  78   69   66  78   85
24  67   94   60  67  100
25  89   87   75  69   87
26  96  100   55  94   65
27  65   73   70  86   59
28  80   64   56  50   95
29  63  100   62  66   79
30  81   86   95  99   85
31  99   55   89  78  100
32  69   66   63  94   97
33  94   50   64  86   89
34  73   50   54  61   77
35  98   80   84  58   87
36  67   70   71  69   81
37  60   61   69  82   97
38  77   80   82  85   52
39  81   54   53  59   50
40  54   92   85  60   91
41  59   98   72  79   78
42  80   63   73  70   51
43  84   91   55  68  100
44  89   50   84  93   63
45  79   66  100  59   97
46  57   64   96  56   73
47  72   58   99  83   53
48  98   67   73  64   90
49  59   66   72  68   64

In [37]:
import random
def get_names(nums:int=10):
    with open('names.txt',encoding ='utf-8') as file:
        content = file.read()
        names = content.split("\n")
        randam_names = random.sample(names,nums)
    return randam_names  
  
get_names()  

['陳志偉', '洪阿惠', '葉志峰', '蘇凡菁', '傅佳琳', '郭淑枝', '黃必琪', '楊綺芬', '彭偉妃', '王雅琴']

In [74]:
number_student = 50
dat = np.random.randint(50,high=101,size=(number_student, 5))
students = pd.DataFrame(dat,
             columns=['國文','英文','數學','地理','探討'],
             index = get_names(number_student))
students
print(type(students))

<class 'pandas.core.frame.DataFrame'>


In [42]:
students.to_csv('student成績.txt')
print('儲存成功')

儲存成功


In [44]:
students.to_excel('student成績.xlsx',sheet_name='6年12班成績')

In [48]:
import pandas as pd
df=pd.read_csv('student.csv',index_col=0)
df

chinese  english  math  history  health
name                                              
student1        97       54    61       95      81
student2        65       66   100       96      73
student3        93       54    84       92      86
student4        64       86    94       77      77
student5        51       71    63       68      53
student6       100       98    72       98      50
student7        79       71    81       71      98
student8        71       97    79      100      94
student9        56       78    85       52      92
student10       50       99    84       52      66
student11       52       78    79       85     100
student12       92       63    97       80      88
student13       96       78    73       69      97
student14       90       52    66       85      86
student15       60       57    52       61      71
student16       55       84    92       86      99
student17       69       76    95       96      77
student18       65       92    92       63      77
student19       90       57    99       83      97
student20       52       99    63       61      53
student21       74       89    68      100      68
student22       52       73    66       65      52
student23       50       64    61       59     100
student24       91       71    63       51      60
student25       65       64    93       98      91
student26       82       58    68       95      52
student27      100       67    96       72      63
student28       70       70    52       65      62
student29       73       56    74       50      99
student30       80      100    82       87      98
student31       74       86    88      100      62
student32       87       74    89       69      64
student33       53       99    83       70      84
student34       91       69    53       70      82
student35       75       96    72       96      50
student36       83       74   100       58      81
student37       78       53    58       80      87
student38       98       87    82       97      65
student39       98       88    90       50      97
student40       87       71    95       98      76
student41       61       85    81       78      54
student42       97       63    73       73      70
student43       72       95    80       69      87
student44       78       96    51       95      84
student45       84       78    81       80      92
student46       95       80    71       88      56
student47       93       53    63       55      54
student48       98       56    99       63      82
student49       60       70    91       76      89
student50       96       83    69       50      79

In [49]:
df = pd.read_excel('student成績.xlsx',index_col=0)
df

國文   英文   數學   地理   探討
胡淑貞  91   55   67   93   67
林冠蕙  87   90   51   75   90
楊少亮  97   76   50   88   98
蔡孟泉  54   88   67   80   98
林柏洋  51   84   98   95   52
李美洋  86   99   81  100   65
王筱婷  56   95   66   88   50
林俊翔  66   67   53   68   67
賴苑禾  57   55  100   63  100
王人仰  78   75   63   76   72
吳孟穎  71   55   98   90   78
洪阿惠  54   84   68   73   98
黃旻林  69   98   95   91   52
趙家豪  86   96   78   77   94
陳向愛  63   55   70   81   67
盧必妍  75   89   58   52   51
陳建豪  53   90   94   88   53
王坤安  84   51   50   74   88
彭茹靖  71   84   96   86   75
羅幸娥  72   69   71   55   77
鄭奇翰  92   55   86   84   65
蘇凡菁  54   63   77   77   75
吳柏誠  62   57   99   71   57
陳得映  97   75   80   96   79
蔡偉成  78   57   74   52   52
吳淑惠  64   58   98   82   75
金宜芳  63   88   83   63   86
吳麗卿  80   98   83   79   63
謝貞妃  83   76   51   93   71
李蓉瑞  51   55   64   91   79
林珈發  61   53   89   86   65
林士凱  84   80   81   62   66
高士凱  63   68   70   91   53
陳奇瑄  61   96   83   52   89
張天亨  66   53   76   68   54
戴萱能  82   56   95   71   56
劉佳佩  59   89   97   55   82
王志謙  59   77   82   57   62
陳筱涵  64   91   79   66   99
陳俊憲  85   69   82   57   59
黃江旭  86   95   75   93   93
方雅慧  90   59  100   83   69
李雅怡  87   64   52   82   94
胡姿婷  92   61   81   98   65
王雅琴  62   55   65   69   55
黃志福  61   73   85   54   76
趙宛真  52  100   86   57   51
張家秀  78   57   96   60   65
李政白  50   90   87   60   74
林詠斌  63   96   53   56   98

In [ ]:
#選取單欄資料
df['國文']

胡淑貞    91
林冠蕙    87
楊少亮    97
蔡孟泉    54
林柏洋    51
李美洋    86
王筱婷    56
林俊翔    66
賴苑禾    57
王人仰    78
吳孟穎    71
洪阿惠    54
黃旻林    69
趙家豪    86
陳向愛    63
盧必妍    75
陳建豪    53
王坤安    84
彭茹靖    71
羅幸娥    72
鄭奇翰    92
蘇凡菁    54
吳柏誠    62
陳得映    97
蔡偉成    78
吳淑惠    64
金宜芳    63
吳麗卿    80
謝貞妃    83
李蓉瑞    51
林珈發    61
林士凱    84
高士凱    63
陳奇瑄    61
張天亨    66
戴萱能    82
劉佳佩    59
王志謙    59
陳筱涵    64
陳俊憲    85
黃江旭    86
方雅慧    90
李雅怡    87
胡姿婷    92
王雅琴    62
黃志福    61
趙宛真    52
張家秀    78
李政白    50
林詠斌    63
Name: 國文, dtype: int64

In [ ]:
#選取多欄資料
df[['國文','數學']]

國文   數學
胡淑貞  91   67
林冠蕙  87   51
楊少亮  97   50
蔡孟泉  54   67
林柏洋  51   98
李美洋  86   81
王筱婷  56   66
林俊翔  66   53
賴苑禾  57  100
王人仰  78   63
吳孟穎  71   98
洪阿惠  54   68
黃旻林  69   95
趙家豪  86   78
陳向愛  63   70
盧必妍  75   58
陳建豪  53   94
王坤安  84   50
彭茹靖  71   96
羅幸娥  72   71
鄭奇翰  92   86
蘇凡菁  54   77
吳柏誠  62   99
陳得映  97   80
蔡偉成  78   74
吳淑惠  64   98
金宜芳  63   83
吳麗卿  80   83
謝貞妃  83   51
李蓉瑞  51   64
林珈發  61   89
林士凱  84   81
高士凱  63   70
陳奇瑄  61   83
張天亨  66   76
戴萱能  82   95
劉佳佩  59   97
王志謙  59   82
陳筱涵  64   79
陳俊憲  85   82
黃江旭  86   75
方雅慧  90  100
李雅怡  87   52
胡姿婷  92   81
王雅琴  62   65
黃志福  61   85
趙宛真  52   86
張家秀  78   96
李政白  50   87
林詠斌  63   53

In [53]:
#loc->使用索引的名稱
#iloc->使用索引的index

df.loc['胡淑貞']
df.loc[['胡淑貞','蔡孟泉']]

國文  英文  數學  地理  探討
胡淑貞  91  55  67  93  67
蔡孟泉  54  88  67  80  98

In [54]:
df.iloc[0]
df.iloc[[0,3]]

國文  英文  數學  地理  探討
胡淑貞  91  55  67  93  67
蔡孟泉  54  88  67  80  98

In [55]:
df.loc['胡淑貞':'蔡孟泉']

國文  英文  數學  地理  探討
胡淑貞  91  55  67  93  67
林冠蕙  87  90  51  75  90
楊少亮  97  76  50  88  98
蔡孟泉  54  88  67  80  98

In [56]:
df.iloc[0:3]

國文  英文  數學  地理  探討
胡淑貞  91  55  67  93  67
林冠蕙  87  90  51  75  90
楊少亮  97  76  50  88  98

In [ ]:
#改胡淑貞的英文成績
df.loc['胡淑貞','英文']=60
df.head()

國文  英文  數學  地理  探討
胡淑貞  91  60  67  93  67
林冠蕙  87  90  51  75  90
楊少亮  97  76  50  88  98
蔡孟泉  54  88  67  80  98
林柏洋  51  84  98  95  52

In [58]:
df[:10]

國文  英文   數學   地理   探討
胡淑貞  91  60   67   93   67
林冠蕙  87  90   51   75   90
楊少亮  97  76   50   88   98
蔡孟泉  54  88   67   80   98
林柏洋  51  84   98   95   52
李美洋  86  99   81  100   65
王筱婷  56  95   66   88   50
林俊翔  66  67   53   68   67
賴苑禾  57  55  100   63  100
王人仰  78  75   63   76   72

In [59]:
df[-10:]

國文   英文   數學  地理  探討
黃江旭  86   95   75  93  93
方雅慧  90   59  100  83  69
李雅怡  87   64   52  82  94
胡姿婷  92   61   81  98  65
王雅琴  62   55   65  69  55
黃志福  61   73   85  54  76
趙宛真  52  100   86  57  51
張家秀  78   57   96  60  65
李政白  50   90   87  60  74
林詠斌  63   96   53  56  98

In [ ]:
df.sum(axis=1)
#也可以寫成這樣:
df['國文']+df['英文']+df['數學']+df['地理']+df['探討']

胡淑貞    378
林冠蕙    393
楊少亮    409
蔡孟泉    387
林柏洋    380
李美洋    431
王筱婷    355
林俊翔    321
賴苑禾    375
王人仰    364
吳孟穎    392
洪阿惠    377
黃旻林    405
趙家豪    431
陳向愛    336
盧必妍    325
陳建豪    378
王坤安    347
彭茹靖    412
羅幸娥    344
鄭奇翰    382
蘇凡菁    346
吳柏誠    346
陳得映    427
蔡偉成    313
吳淑惠    377
金宜芳    383
吳麗卿    403
謝貞妃    374
李蓉瑞    340
林珈發    354
林士凱    373
高士凱    345
陳奇瑄    381
張天亨    317
戴萱能    360
劉佳佩    382
王志謙    337
陳筱涵    399
陳俊憲    352
黃江旭    442
方雅慧    401
李雅怡    379
胡姿婷    397
王雅琴    306
黃志福    349
趙宛真    346
張家秀    356
李政白    361
林詠斌    366
dtype: int64

In [ ]:
#剛提到的df.sum，我先儲存在一個變數
stu_total = df.sum(axis=1)
#計算平均
stu_mean = df.mean(axis=1)
#計算平均也可以寫成
stu_mean = stu_sum / 5.0

胡淑貞    75.6
林冠蕙    78.6
楊少亮    81.8
蔡孟泉    77.4
林柏洋    76.0
李美洋    86.2
王筱婷    71.0
林俊翔    64.2
賴苑禾    75.0
王人仰    72.8
吳孟穎    78.4
洪阿惠    75.4
黃旻林    81.0
趙家豪    86.2
陳向愛    67.2
盧必妍    65.0
陳建豪    75.6
王坤安    69.4
彭茹靖    82.4
羅幸娥    68.8
鄭奇翰    76.4
蘇凡菁    69.2
吳柏誠    69.2
陳得映    85.4
蔡偉成    62.6
吳淑惠    75.4
金宜芳    76.6
吳麗卿    80.6
謝貞妃    74.8
李蓉瑞    68.0
林珈發    70.8
林士凱    74.6
高士凱    69.0
陳奇瑄    76.2
張天亨    63.4
戴萱能    72.0
劉佳佩    76.4
王志謙    67.4
陳筱涵    79.8
陳俊憲    70.4
黃江旭    88.4
方雅慧    80.2
李雅怡    75.8
胡姿婷    79.4
王雅琴    61.2
黃志福    69.8
趙宛真    69.2
張家秀    71.2
李政白    72.2
林詠斌    73.2
dtype: float64

In [70]:
df['總分'] = stu_total
df['平均'] = stu_mean
#此時就會新增兩欄，分別是總分和平均
df

國文   英文   數學   地理   探討   總分    平均
胡淑貞  91   60   67   93   67  378  75.6
林冠蕙  87   90   51   75   90  393  78.6
楊少亮  97   76   50   88   98  409  81.8
蔡孟泉  54   88   67   80   98  387  77.4
林柏洋  51   84   98   95   52  380  76.0
李美洋  86   99   81  100   65  431  86.2
王筱婷  56   95   66   88   50  355  71.0
林俊翔  66   67   53   68   67  321  64.2
賴苑禾  57   55  100   63  100  375  75.0
王人仰  78   75   63   76   72  364  72.8
吳孟穎  71   55   98   90   78  392  78.4
洪阿惠  54   84   68   73   98  377  75.4
黃旻林  69   98   95   91   52  405  81.0
趙家豪  86   96   78   77   94  431  86.2
陳向愛  63   55   70   81   67  336  67.2
盧必妍  75   89   58   52   51  325  65.0
陳建豪  53   90   94   88   53  378  75.6
王坤安  84   51   50   74   88  347  69.4
彭茹靖  71   84   96   86   75  412  82.4
羅幸娥  72   69   71   55   77  344  68.8
鄭奇翰  92   55   86   84   65  382  76.4
蘇凡菁  54   63   77   77   75  346  69.2
吳柏誠  62   57   99   71   57  346  69.2
陳得映  97   75   80   96   79  427  85.4
蔡偉成  78   57   74   52   52  313  62.6
吳淑惠  64   58   98   82   75  377  75.4
金宜芳  63   88   83   63   86  383  76.6
吳麗卿  80   98   83   79   63  403  80.6
謝貞妃  83   76   51   93   71  374  74.8
李蓉瑞  51   55   64   91   79  340  68.0
林珈發  61   53   89   86   65  354  70.8
林士凱  84   80   81   62   66  373  74.6
高士凱  63   68   70   91   53  345  69.0
陳奇瑄  61   96   83   52   89  381  76.2
張天亨  66   53   76   68   54  317  63.4
戴萱能  82   56   95   71   56  360  72.0
劉佳佩  59   89   97   55   82  382  76.4
王志謙  59   77   82   57   62  337  67.4
陳筱涵  64   91   79   66   99  399  79.8
陳俊憲  85   69   82   57   59  352  70.4
黃江旭  86   95   75   93   93  442  88.4
方雅慧  90   59  100   83   69  401  80.2
李雅怡  87   64   52   82   94  379  75.8
胡姿婷  92   61   81   98   65  397  79.4
王雅琴  62   55   65   69   55  306  61.2
黃志福  61   73   85   54   76  349  69.8
趙宛真  52  100   86   57   51  346  69.2
張家秀  78   57   96   60   65  356  71.2
李政白  50   90   87   60   74  361  72.2
林詠斌  63   96   53   56   98  366  73.2

In [ ]:
#把一開始用url抓的youbike的datal(是list+dict的資料結構)放進來
import requests

url = 'https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json'
response = requests.get(url)
datal = response.json()

def func(n):
    return n['available_rent_bikes'] == 0

zero_rent_bikes = list(filter(func,datal))
#把一開始用url抓的youbike的datal(是list+dict的資料結構)變成dataframe實體(因為datal是二維的資料；如果是一維資料，要用pd看，就要用series轉成series實體)
df = pd.DataFrame(datal)#轉變成dataframe實體
df[["sna",'sarea','mday','ar','available_rent_bikes','available_return_bikes','total']]


sna   sarea                 mday             ar  \
0         YouBike2.0_捷運科技大樓站     大安區  2025-02-15 16:15:18    復興南路二段235號前   
1     YouBike2.0_復興南路二段273號前     大安區  2025-02-15 16:12:15   復興南路二段273號西側   
2       YouBike2.0_國北教大實小東側門     大安區  2025-02-15 16:13:16    和平東路二段96巷7號   
3          YouBike2.0_和平公園東側     大安區  2025-02-15 16:12:16  和平東路二段118巷33號   
4       YouBike2.0_辛亥復興路口西北側     大安區  2025-02-15 16:14:17     復興南路二段368號   
...                      ...     ...                  ...            ...   
1523      YouBike2.0_臺大禮賢樓西側  臺大公館校區  2025-02-15 15:04:18      臺大禮賢樓西側空地   
1524    YouBike2.0_臺大大一女餐廳廣場  臺大公館校區  2025-02-15 16:10:29    臺大大一女餐廳廣場後方   
1525        YouBike2.0_臺大學新館  臺大公館校區  2025-02-15 16:13:16         臺大學新館旁   
1526     YouBike2.0_臺大水源舍區C棟  臺大公館校區  2025-02-15 16:06:18     臺大水源舍區C棟西側   
1527        YouBike2.0_臺大人文館  臺大公館校區  2025-02-15 16:12:15       臺大人文館東北側   

      available_rent_bikes  available_return_bikes  total  
0                        5                      23     28  
1                        6                      15     21  
2                        8                       8     16  
3                        6                       5     11  
4                        9                       7     16  
...                    ...                     ...    ...  
1523                    18                      18     36  
1524                    11                      13     40  
1525                     1                      32     33  
1526                    16                      82     99  
1527                    28                      39     67  

[1528 rows x 7 columns]