In [4]:
import requests

url = 'https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json'
response = requests.get(url)
data = response.json()

def func(n):
    return n['available_rent_bikes'] == 0

zero_rent_bikes = list(filter(func,data))
print(len(zero_rent_bikes))
for site in zero_rent_bikes:
    print(site['sna'])

66
YouBike2.0_和平公園東側
YouBike2.0_復興南路二段340巷口
YouBike2.0_溫州停車場
YouBike2.0_和平龍泉街口
YouBike2.0_捷運古亭站(5號出口)
YouBike2.0_昌隆公園
YouBike2.0_敦化市民路口
YouBike2.0_懷生國中
YouBike2.0_臺灣師範大學(浦城街)
YouBike2.0_民權延平路口(西北側)
YouBike2.0_捷運北門站(3號出口)
YouBike2.0_南京太原路口
YouBike2.0_雙蓮國小
YouBike2.0_南京西寧北路口(西北側)
YouBike2.0_劍潭抽水站
YouBike2.0_銘傳大學
YouBike2.0_社子國小
YouBike2.0_文林路101巷口
YouBike2.0_海光公園南側
YouBike2.0_天母東路8巷/忠誠路二段154巷口
YouBike2.0_景美運動公園
YouBike2.0_興得閱覽室
YouBike2.0_木南公園
YouBike2.0_捷運動物園站(2號出口)
YouBike2.0_名門社區
YouBike2.0_捷運古亭站(9號出口)
YouBike2.0_和平重慶路口
YouBike2.0_捷運小南門站(1號出口)
YouBike2.0_林森徐州路口
YouBike2.0_羅斯福寧波東街口
YouBike2.0_捷運臺大醫院站(1號出口)
YouBike2.0_捷運中正紀念堂站(2號出口)
YouBike2.0_螢橋公園
YouBike2.0_公館水岸廣場
YouBike2.0_捷運行天宮站(3號出口)
YouBike2.0_新生高架停車場(林森北路107巷口)
YouBike2.0_中山北路二段59巷口
YouBike2.0_興安合江路口
YouBike2.0_復華公園
YouBike2.0_敬業三樂群三路口(西北側)
YouBike2.0_長春路258巷2弄口
YouBike2.0_中崙加油站
YouBike2.0_中正國小(南京東路三段48巷)
YouBike2.0_文德二號公園(南側)
YouBike2.0_瑞陽公園
YouBike2.0_碧湖公園(內湖路二段103巷)
YouBike2.0_石潭公園(安康路)
YouBike2.0_奇岩一號公園
YouBike2.0_立功街55巷口
Yo

In [5]:
scores = [78,69,87]
new_scores = []

for score in scores:
    new_scores.append(score+3)

new_scores

[81, 72, 90]

In [6]:
#list comprehention(快速建立list)
scores = [78, 69, 65]
new_scores = [score+3 for score in scores]
new_scores

[81, 72, 68]

In [7]:
scores = [78, 69, 65]
scores * 2

[78, 69, 65, 78, 69, 65]

In [8]:
[67, 92, 85] + [78, 69, 65]

[67, 92, 85, 78, 69, 65]

In [9]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [10]:
scores.sum()
scores.mean()
scores.std()
scores.min()
scores.max()
np.median(scores)

np.float64(69.0)

In [11]:
students = np.array([
    [67, 94, 65],
    [78, 92, 68],
    [59, 92, 87]
    ])
students
#三位學生的三科成績資料

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [12]:
#常用的查詢屬性
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [13]:
students[0,0]

np.int64(67)

In [14]:
#第1位學生分數
students[0,:]

array([67, 94, 65])

In [15]:
#前2個學生
students[0:2,:]

array([[67, 94, 65],
       [78, 92, 68]])

In [22]:
#最後2個學生成績加3分
students[-2:,:] + 3

array([[81, 95, 71],
       [62, 95, 90]])

In [17]:
#第一欄分數
students[:,0]


array([67, 78, 59])

In [18]:
students[:,:2]

array([[67, 94],
       [78, 92],
       [59, 92]])

In [26]:
students[0,0] = 100
students

array([[100,  94,  65],
       [ 78,  92,  68],
       [ 59,  92,  87]])

In [28]:
students[-2:,:] +=3
students[-2:,:]

array([[84, 98, 74],
       [65, 98, 93]])

In [34]:
import pandas as pd
pd.DataFrame(data=students,
             index=['stud1','stud2','stud3'],
             columns =['國文','英文','數學']
             )

國文  英文  數學
stud1  100  94  65
stud2   84  98  74
stud3   65  98  93

In [35]:
data = np.random.randint(50,high=101,size=(50, 5))
students = pd.DataFrame(data,
             columns=['國文','英文','數學','地理','探討'])
students

國文   英文   數學   地理  探討
0    91   96   58   55  83
1    87   79   52   57  95
2    98   62   87   88  54
3    50   54   84   99  92
4    55   94   73   76  66
5    71   51   54   83  69
6    66   93   89   62  72
7    65   61   89   89  53
8    98   95   96   56  64
9    96   96   53  100  62
10   77   93   51   52  92
11   63   97   85   82  94
12   84   70   76   96  88
13   67   77   88   81  73
14   74   59   95   60  65
15   94   53   55   96  74
16   86   86   56   61  79
17   52   84   85   78  76
18   86   64   76   89  70
19   75  100  100   69  59
20   56   67   73   58  89
21   86   52   55   63  81
22   56   88   69   53  68
23   72   76   57   85  50
24   90   88   79   88  73
25   62   70   91   74  96
26   97   62   97   71  75
27   65   53  100   56  83
28   86   77   72   85  61
29   63   52   68   89  82
30   77   91   52   89  89
31   86   92   75   98  58
32   51   58   53   82  50
33   60   77   94   99  75
34   90   50   89   97  67
35   82   84   57   89  73
36   92   83   54   93  80
37   61   54   84   98  83
38   81  100   75   68  63
39   54   63   77   86  67
40   63   99   93   73  79
41  100   95   66   72  85
42   94   75   51   74  61
43   93   91   81   96  88
44   73   75   98   63  60
45   84   89   87   83  77
46   55   69   78   63  88
47   55  100   86   57  58
48   96   62   51   91  86
49   56   64   73   57  50

In [37]:
import random
def get_names(nums:int=10):
    with open('names.txt',encoding ='utf-8') as file:
        content = file.read()
        names = content.split("\n")
        randam_names = random.sample(names,nums)
    return randam_names  
  
get_names()  

['陳志偉', '洪阿惠', '葉志峰', '蘇凡菁', '傅佳琳', '郭淑枝', '黃必琪', '楊綺芬', '彭偉妃', '王雅琴']

In [41]:
number_student = 50
data = np.random.randint(50,high=101,size=(number_student, 5))
students = pd.DataFrame(data,
             columns=['國文','英文','數學','地理','探討'],
             index = get_names(number_student))
students
print(type(students))

<class 'pandas.core.frame.DataFrame'>


In [42]:
students.to_csv('student成績.txt')
print('儲存成功')

儲存成功


In [44]:
students.to_excel('student成績.xlsx',sheet_name='6年12班成績')

In [48]:
import pandas as pd
df=pd.read_csv('student.csv',index_col=0)
df

chinese  english  math  history  health
name                                              
student1        97       54    61       95      81
student2        65       66   100       96      73
student3        93       54    84       92      86
student4        64       86    94       77      77
student5        51       71    63       68      53
student6       100       98    72       98      50
student7        79       71    81       71      98
student8        71       97    79      100      94
student9        56       78    85       52      92
student10       50       99    84       52      66
student11       52       78    79       85     100
student12       92       63    97       80      88
student13       96       78    73       69      97
student14       90       52    66       85      86
student15       60       57    52       61      71
student16       55       84    92       86      99
student17       69       76    95       96      77
student18       65       92    92       63      77
student19       90       57    99       83      97
student20       52       99    63       61      53
student21       74       89    68      100      68
student22       52       73    66       65      52
student23       50       64    61       59     100
student24       91       71    63       51      60
student25       65       64    93       98      91
student26       82       58    68       95      52
student27      100       67    96       72      63
student28       70       70    52       65      62
student29       73       56    74       50      99
student30       80      100    82       87      98
student31       74       86    88      100      62
student32       87       74    89       69      64
student33       53       99    83       70      84
student34       91       69    53       70      82
student35       75       96    72       96      50
student36       83       74   100       58      81
student37       78       53    58       80      87
student38       98       87    82       97      65
student39       98       88    90       50      97
student40       87       71    95       98      76
student41       61       85    81       78      54
student42       97       63    73       73      70
student43       72       95    80       69      87
student44       78       96    51       95      84
student45       84       78    81       80      92
student46       95       80    71       88      56
student47       93       53    63       55      54
student48       98       56    99       63      82
student49       60       70    91       76      89
student50       96       83    69       50      79

In [49]:
df = pd.read_excel('student成績.xlsx',index_col=0)
df

國文   英文   數學   地理   探討
胡淑貞  91   55   67   93   67
林冠蕙  87   90   51   75   90
楊少亮  97   76   50   88   98
蔡孟泉  54   88   67   80   98
林柏洋  51   84   98   95   52
李美洋  86   99   81  100   65
王筱婷  56   95   66   88   50
林俊翔  66   67   53   68   67
賴苑禾  57   55  100   63  100
王人仰  78   75   63   76   72
吳孟穎  71   55   98   90   78
洪阿惠  54   84   68   73   98
黃旻林  69   98   95   91   52
趙家豪  86   96   78   77   94
陳向愛  63   55   70   81   67
盧必妍  75   89   58   52   51
陳建豪  53   90   94   88   53
王坤安  84   51   50   74   88
彭茹靖  71   84   96   86   75
羅幸娥  72   69   71   55   77
鄭奇翰  92   55   86   84   65
蘇凡菁  54   63   77   77   75
吳柏誠  62   57   99   71   57
陳得映  97   75   80   96   79
蔡偉成  78   57   74   52   52
吳淑惠  64   58   98   82   75
金宜芳  63   88   83   63   86
吳麗卿  80   98   83   79   63
謝貞妃  83   76   51   93   71
李蓉瑞  51   55   64   91   79
林珈發  61   53   89   86   65
林士凱  84   80   81   62   66
高士凱  63   68   70   91   53
陳奇瑄  61   96   83   52   89
張天亨  66   53   76   68   54
戴萱能  82   56   95   71   56
劉佳佩  59   89   97   55   82
王志謙  59   77   82   57   62
陳筱涵  64   91   79   66   99
陳俊憲  85   69   82   57   59
黃江旭  86   95   75   93   93
方雅慧  90   59  100   83   69
李雅怡  87   64   52   82   94
胡姿婷  92   61   81   98   65
王雅琴  62   55   65   69   55
黃志福  61   73   85   54   76
趙宛真  52  100   86   57   51
張家秀  78   57   96   60   65
李政白  50   90   87   60   74
林詠斌  63   96   53   56   98

In [50]:
df['國文']

胡淑貞    91
林冠蕙    87
楊少亮    97
蔡孟泉    54
林柏洋    51
李美洋    86
王筱婷    56
林俊翔    66
賴苑禾    57
王人仰    78
吳孟穎    71
洪阿惠    54
黃旻林    69
趙家豪    86
陳向愛    63
盧必妍    75
陳建豪    53
王坤安    84
彭茹靖    71
羅幸娥    72
鄭奇翰    92
蘇凡菁    54
吳柏誠    62
陳得映    97
蔡偉成    78
吳淑惠    64
金宜芳    63
吳麗卿    80
謝貞妃    83
李蓉瑞    51
林珈發    61
林士凱    84
高士凱    63
陳奇瑄    61
張天亨    66
戴萱能    82
劉佳佩    59
王志謙    59
陳筱涵    64
陳俊憲    85
黃江旭    86
方雅慧    90
李雅怡    87
胡姿婷    92
王雅琴    62
黃志福    61
趙宛真    52
張家秀    78
李政白    50
林詠斌    63
Name: 國文, dtype: int64

In [51]:
df[['國文','數學']]

國文   數學
胡淑貞  91   67
林冠蕙  87   51
楊少亮  97   50
蔡孟泉  54   67
林柏洋  51   98
李美洋  86   81
王筱婷  56   66
林俊翔  66   53
賴苑禾  57  100
王人仰  78   63
吳孟穎  71   98
洪阿惠  54   68
黃旻林  69   95
趙家豪  86   78
陳向愛  63   70
盧必妍  75   58
陳建豪  53   94
王坤安  84   50
彭茹靖  71   96
羅幸娥  72   71
鄭奇翰  92   86
蘇凡菁  54   77
吳柏誠  62   99
陳得映  97   80
蔡偉成  78   74
吳淑惠  64   98
金宜芳  63   83
吳麗卿  80   83
謝貞妃  83   51
李蓉瑞  51   64
林珈發  61   89
林士凱  84   81
高士凱  63   70
陳奇瑄  61   83
張天亨  66   76
戴萱能  82   95
劉佳佩  59   97
王志謙  59   82
陳筱涵  64   79
陳俊憲  85   82
黃江旭  86   75
方雅慧  90  100
李雅怡  87   52
胡姿婷  92   81
王雅琴  62   65
黃志福  61   85
趙宛真  52   86
張家秀  78   96
李政白  50   87
林詠斌  63   53