In [4]:
import requests

url = 'https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json'
response = requests.get(url)
data = response.json()

def func(n):
    return n['available_rent_bikes'] == 0

zero_rent_bikes = list(filter(func,data))
print(len(zero_rent_bikes))
for site in zero_rent_bikes:
    print(site['sna'])

66
YouBike2.0_和平公園東側
YouBike2.0_復興南路二段340巷口
YouBike2.0_溫州停車場
YouBike2.0_和平龍泉街口
YouBike2.0_捷運古亭站(5號出口)
YouBike2.0_昌隆公園
YouBike2.0_敦化市民路口
YouBike2.0_懷生國中
YouBike2.0_臺灣師範大學(浦城街)
YouBike2.0_民權延平路口(西北側)
YouBike2.0_捷運北門站(3號出口)
YouBike2.0_南京太原路口
YouBike2.0_雙蓮國小
YouBike2.0_南京西寧北路口(西北側)
YouBike2.0_劍潭抽水站
YouBike2.0_銘傳大學
YouBike2.0_社子國小
YouBike2.0_文林路101巷口
YouBike2.0_海光公園南側
YouBike2.0_天母東路8巷/忠誠路二段154巷口
YouBike2.0_景美運動公園
YouBike2.0_興得閱覽室
YouBike2.0_木南公園
YouBike2.0_捷運動物園站(2號出口)
YouBike2.0_名門社區
YouBike2.0_捷運古亭站(9號出口)
YouBike2.0_和平重慶路口
YouBike2.0_捷運小南門站(1號出口)
YouBike2.0_林森徐州路口
YouBike2.0_羅斯福寧波東街口
YouBike2.0_捷運臺大醫院站(1號出口)
YouBike2.0_捷運中正紀念堂站(2號出口)
YouBike2.0_螢橋公園
YouBike2.0_公館水岸廣場
YouBike2.0_捷運行天宮站(3號出口)
YouBike2.0_新生高架停車場(林森北路107巷口)
YouBike2.0_中山北路二段59巷口
YouBike2.0_興安合江路口
YouBike2.0_復華公園
YouBike2.0_敬業三樂群三路口(西北側)
YouBike2.0_長春路258巷2弄口
YouBike2.0_中崙加油站
YouBike2.0_中正國小(南京東路三段48巷)
YouBike2.0_文德二號公園(南側)
YouBike2.0_瑞陽公園
YouBike2.0_碧湖公園(內湖路二段103巷)
YouBike2.0_石潭公園(安康路)
YouBike2.0_奇岩一號公園
YouBike2.0_立功街55巷口
Yo

In [5]:
scores = [78,69,87]
new_scores = []

for score in scores:
    new_scores.append(score+3)

new_scores

[81, 72, 90]

In [6]:
#list comprehention(快速建立list)
scores = [78, 69, 65]
new_scores = [score+3 for score in scores]
new_scores

[81, 72, 68]

In [7]:
scores = [78, 69, 65]
scores * 2

[78, 69, 65, 78, 69, 65]

In [8]:
[67, 92, 85] + [78, 69, 65]

[67, 92, 85, 78, 69, 65]

In [9]:
import numpy as np

scores = np.array([78, 69, 65])
print(type(scores))
scores + 3

<class 'numpy.ndarray'>


array([81, 72, 68])

In [10]:
scores.sum()
scores.mean()
scores.std()
scores.min()
scores.max()
np.median(scores)

np.float64(69.0)

In [11]:
students = np.array([
    [67, 94, 65],
    [78, 92, 68],
    [59, 92, 87]
    ])
students
#三位學生的三科成績資料

array([[67, 94, 65],
       [78, 92, 68],
       [59, 92, 87]])

In [12]:
#常用的查詢屬性
students.ndim, students.size, students.shape, students.dtype

(2, 9, (3, 3), dtype('int64'))

In [13]:
students[0,0]

np.int64(67)

In [14]:
#第1位學生分數
students[0,:]

array([67, 94, 65])

In [15]:
#前2個學生
students[0:2,:]

array([[67, 94, 65],
       [78, 92, 68]])

In [22]:
#最後2個學生成績加3分
students[-2:,:] + 3

array([[81, 95, 71],
       [62, 95, 90]])

In [17]:
#第一欄分數
students[:,0]


array([67, 78, 59])

In [18]:
students[:,:2]

array([[67, 94],
       [78, 92],
       [59, 92]])

In [26]:
students[0,0] = 100
students

array([[100,  94,  65],
       [ 78,  92,  68],
       [ 59,  92,  87]])

In [28]:
students[-2:,:] +=3
students[-2:,:]

array([[84, 98, 74],
       [65, 98, 93]])

In [34]:
import pandas as pd
pd.DataFrame(data=students,
             index=['stud1','stud2','stud3'],
             columns =['國文','英文','數學']
             )

國文  英文  數學
stud1  100  94  65
stud2   84  98  74
stud3   65  98  93

In [35]:
data = np.random.randint(50,high=101,size=(50, 5))
students = pd.DataFrame(data,
             columns=['國文','英文','數學','地理','探討'])
students

國文   英文   數學   地理  探討
0    91   96   58   55  83
1    87   79   52   57  95
2    98   62   87   88  54
3    50   54   84   99  92
4    55   94   73   76  66
5    71   51   54   83  69
6    66   93   89   62  72
7    65   61   89   89  53
8    98   95   96   56  64
9    96   96   53  100  62
10   77   93   51   52  92
11   63   97   85   82  94
12   84   70   76   96  88
13   67   77   88   81  73
14   74   59   95   60  65
15   94   53   55   96  74
16   86   86   56   61  79
17   52   84   85   78  76
18   86   64   76   89  70
19   75  100  100   69  59
20   56   67   73   58  89
21   86   52   55   63  81
22   56   88   69   53  68
23   72   76   57   85  50
24   90   88   79   88  73
25   62   70   91   74  96
26   97   62   97   71  75
27   65   53  100   56  83
28   86   77   72   85  61
29   63   52   68   89  82
30   77   91   52   89  89
31   86   92   75   98  58
32   51   58   53   82  50
33   60   77   94   99  75
34   90   50   89   97  67
35   82   84   57   89  73
36   92   83   54   93  80
37   61   54   84   98  83
38   81  100   75   68  63
39   54   63   77   86  67
40   63   99   93   73  79
41  100   95   66   72  85
42   94   75   51   74  61
43   93   91   81   96  88
44   73   75   98   63  60
45   84   89   87   83  77
46   55   69   78   63  88
47   55  100   86   57  58
48   96   62   51   91  86
49   56   64   73   57  50

In [37]:
import random
def get_names(nums:int=10):
    with open('names.txt',encoding ='utf-8') as file:
        content = file.read()
        names = content.split("\n")
        randam_names = random.sample(names,nums)
    return randam_names  
  
get_names()  

['陳志偉', '洪阿惠', '葉志峰', '蘇凡菁', '傅佳琳', '郭淑枝', '黃必琪', '楊綺芬', '彭偉妃', '王雅琴']

In [40]:
number_student = 50
data = np.random.randint(50,high=101,size=(number_student, 5))
students = pd.DataFrame(data,
             columns=['國文','英文','數學','地理','探討'],
             index = get_names(number_student))
students

國文  英文  數學  地理   探討
黃心航   55  93  57  70   92
高俊男   90  65  71  90   86
沈心利   67  78  73  92   64
王坤安   84  95  90  95   50
吳昕婷   81  58  86  81   77
楊偉翔   87  65  86  92   89
蔡世馨   87  57  65  69   93
林柏洋   69  57  96  86   93
郎慧萍   57  86  95  65   87
景歡燦   66  64  76  94   63
白世宏   73  65  63  59   97
陳俊憲   94  52  65  78   93
謝哲維   89  73  69  60   59
高士凱   94  54  79  69   97
傅佳琳   52  86  89  69   85
王梅劭   98  67  81  51   95
黃彥孝   87  81  87  96   59
黃偉剛   90  74  81  50  100
郭坤花   61  61  71  77   66
陳志偉   75  87  56  57   68
陳怡珊   67  71  88  74   90
張婕妤   72  56  91  74   83
陳淑萍   75  99  75  67   65
趙偉銘   86  67  97  93   62
蕭淑華   57  54  71  91   66
溫法堯   84  90  55  54   69
陳冠霞   89  95  60  80   69
謝水儒   66  92  60  81   75
龔姵君  100  73  97  81   84
藍哲嘉   78  51  51  67   89
吳晴洋   75  90  97  59   61
吳柏誠   83  98  61  73   97
羅佩樺   50  99  67  51  100
劉昀天   83  78  63  66   72
蔡嘉音   89  90  87  92   80
陳家維   92  96  66  75   68
鄭淑珍   68  90  97  53   91
賴昌韻   59  66  63  73   97
林志成   96  96  82  51   76
王怡君   55  64  80  91   71
吳志宣   95  98  62  72   88
郭致恬   71  69  96  93   52
王泓泰   70  70  68  53   86
孫宜珊   64  88  68  82   64
李彥伸   59  61  60  93   67
楊又源   51  51  91  86   67
劉旭士   97  93  56  93   76
林珈發   79  53  63  90   89
簡美君   54  60  92  78   99
吳明妮   56  79  77  61   51